build_draft = false
allow_unsafe_html = true
clean_build = true
base_template_path = "base.tmpl"

[rss]
generate = true
title = "Patrick Dewey"
description = ""
url = "pdewey.com"

[[routes]]
content_path = "index.md"
output_pattern = "/"
template = "_index.tmpl"

[[routes]]
content_path = "blog.md"
output_pattern = "/blog/"
template = "blog.tmpl"

[[routes]]
content_path = "blog"
output_pattern = "/blog/:slug"
template = "post.tmpl"
generate_rss = true

[[routes]]
content_path = "projects.md"
output_pattern = "/projects/"
template = "projects.tmpl"

[[routes]]
content_path = "coffee.md"
output_pattern = "/coffee/"
template = "coffee.tmpl"

[[routes]]
content_path = "now.md"
output_pattern = "/now/"
template = "now.tmpl"

[atproto]
handle = "pdewey.com"
