build_draft = false
allow_unsafe_html = true
clean_build = true
base_template_path = "base.tmpl"

[[routes]]
content_path = "index.md"
output_pattern = "/"
template = "_index.tmpl"

[[routes]]
content_path = "blog.md"
output_pattern = "/blog/"
template = "blog.tmpl"

[[routes]]
content_path = "blog"
output_pattern = "/blog/:slug"
template = "post.tmpl"
generate_rss = true
publish = "blog"

[[routes]]
content_path = "projects.md"
output_pattern = "/projects/"
template = "projects.tmpl"

[[routes]]
content_path = "coffee.md"
output_pattern = "/coffee/"
template = "coffee.tmpl"

[[routes]]
content_path = "now.md"
output_pattern = "/now/"
template = "now.tmpl"

[rss]
generate = true
title = "Patrick Dewey"
description = "Patrick's blog"
url = "pdewey.com"

[atproto]
handle = "pdewey.com"

[atproto.publications.blog]
name = "Patrick's Blog"
rkey = "3mgj4qfasw32n"
url = "https://pdewey.com/blog"
description = "Patrick's personal blog"
show_in_discover = true
include_in_build = false
content_type = "markdown"
path_mode = "slug"
